services:
  - type: web
    name: clipper-api-final-1
    env: python
    plan: standard
    branch: main
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    buildCommand: pip install -r requirements.txt
    autoDeploy: true
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 20
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: UVICORN_WORKERS
        value: 1
      - key: UVICORN_LIMIT_MAX_REQUEST_SIZE
        value: "5000000000" # 5GB limit
      - key: UVICORN_TIMEOUT_KEEP_ALIVE
        value: "120"
